### ISSUE TITLE
Please do not commit to `master`, use `Pull Requests`

### ISSUE THREAD

**Issue by builtbyproxy** [SheCodesAus/layer_8_victory_backend_bris_2023#1]
Hello @rosiemaguire @mayadomi @oriyannadav @Andrea-Rivera @(Jenny what is your github 😂)

Please ensure you are utilising Pull Requests. It's really important for me as your client to understand what is being commited and why. Commits straight to master confuse me and I want to understand the code I am buying. 

Thank you

**Comment by rosiemaguire** [comment]
Hey Lachie,
We were just following the instructions given to us from Ollie in the [README](https://github.com/SheCodesAus/layer_8_victory_backend_bris_2023#readme) as per the initial commit. All subsequent commits have been made to other branches. Also, we are using main over master.
Let me know if you've got any questions surrounding the initial commit or the branches we are working off.
For your reference, they are deployment, which we are using in lieu of having a staging environment, and we are currently working on building out the views and serializers in the views_and_serializers branch.
We are yet to use Pull Requests, but will do once we are at the stage of being ready to merge changes.
Cheers.

**Comment by rosiemaguire** [comment]
I have also just created a rule for the repo that branches cannot be merged to main without a Pull Request with at least one approver :)

**Comment by builtbyproxy** [comment]
Thanks @rosiemaguire that's helpful context!

Pull Requests are a very good process to get familiar with. Thanks for adding that branch protection, feel free to remove it should you get closer to submission and need quick fixes, however for now context through Pull Requests is going to be very beneficial 👍

**Comment by rosiemaguire** [comment]
My pleasure. Are you comfortable that this issue is now resolved?

**Comment by builtbyproxy** [comment]
Yep! Thank you
